# Generated by Django 4.1.7 on 2023-10-07 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_listings_is_on_watchlist_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listings',
            name='current_bid',
        ),
    ]
