# Generated by Django 4.1.7 on 2023-10-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auction_listings_id_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='image',
            field=models.ImageField(default='img', upload_to='auctions/'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='Comment',
            field=models.CharField(default='', max_length=50),
        ),
    ]
